# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 05:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import superintendence.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel', models.CharField(max_length=200)),
                ('ata_eta_mom', models.DateField()),
                ('ocean_del_terms', models.CharField(blank=True, max_length=10, null=True)),
                ('bl_teu', models.IntegerField(blank=True, null=True)),
                ('bl_feu', models.IntegerField(blank=True, null=True)),
                ('cf_agent', models.CharField(blank=True, max_length=20, null=True)),
                ('bl_number', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_disch_loaded', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ex_si_number_po_number', models.CharField(blank=True, max_length=500, null=True)),
                ('commodity', models.CharField(blank=True, max_length=50, null=True)),
                ('pack', models.CharField(blank=True, max_length=10, null=True)),
                ('recipient_country', models.CharField(blank=True, max_length=20, null=True)),
                ('project_type', models.CharField(blank=True, max_length=20, null=True)),
                ('sgs_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='foo_bar', max_length=75, verbose_name='Default')),
            ],
        ),
        migrations.CreateModel(
            name='WithDynamicDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=superintendence.models.random_name, max_length=100, verbose_name='Dyn Default')),
            ],
        ),
        migrations.CreateModel(
            name='WithFloatField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
