# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superintendence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='qty_disch_loaded',
            new_name='tonnage',
        ),
        migrations.AddField(
            model_name='shipment',
            name='po_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ses_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
